server:
    port: 8080
    context-path: /myexample
    
logging:
  config: ./config/log4j.xml
  
spring:
  data:
    mongodb:
      database: myexample
      host: localhost
      port: 27017
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: p@ssw0rd
    test-on-borrow: true
    validation-query: SELECT 1
   
info: 
  app:
    name : "Actuator Example"
    description : "Example with Spring Actuater"
    version : "1.0"
    
    
    
    
